services:
  # PHP + Apache
  app:
    build:
      context: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - egor-network

  # MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - egor-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - egor-network

volumes:
  db_data:

networks:
  egor-network: